import { ReactNode } from 'react';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Korpen Vellinge',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className="bg-zinc-100">{children}</body>
    </html>
  );
};

export default RootLayout;
