import { Metadata } from 'next';
import SignIn from '~/components/sign-in';
import useServerSession from '~/lib/sessions';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Korpen Vellinge - Logga in',
  description: 'Generated by create next app',
};

const SignInPage = async () => {
  const session = await useServerSession();

  if (session) redirect('/dashboard');

  return (
    <div className="w-full px-8 sm:max-w-md">
      <SignIn />
    </div>
  );
};

export default SignInPage;
