import { Metadata } from 'next';
import SignIn from '~/components/sign-in';
import useServerSession from '~/lib/sessions';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Korpen Vellinge - Logga in',
  description: 'Generated by create next app',
};

const SignInPage = async () => {
  const session = await useServerSession();

  if (session) redirect('/');

  return <SignIn />;
};

export default SignInPage;
